In [1]:
num=2.5
type(num)

float

In [2]:
num=15
type(num)

int

In [3]:
num=1+2j
type(num)

complex

In [6]:
a=5.6
b=int(a)
type(b)
b

5

In [11]:
k=float(b)
k

5.0

In [13]:
k=6
c=complex(b,k)
c

(5+6j)

In [14]:
b<k

True

In [15]:
int(True)

1

In [18]:
list=[12,25,44,15,25]
type(list)
list

[12, 25, 44, 15, 25]

In [19]:
set={12,25,44,15,25}
type(set)
set

{12, 15, 25, 44}

In [22]:
t=(12,25,44,15,25)
type(t)
t

(12, 25, 44, 15, 25)

In [24]:
s="ananya"
s

'ananya'

In [25]:
range(10)

range(0, 10)

In [38]:
list(range(11))

TypeError: 'list' object is not callable

In [30]:
list(range(2,10,2))

TypeError: 'list' object is not callable

In [32]:
type(range(10))

range

In [34]:
d={'ananya':'samsumg','raj':'iphone','sahana':'oneplus'}
d.keys()

dict_keys(['ananya', 'raj', 'sahana'])

In [39]:
d.values()

dict_values(['samsumg', 'iphone', 'oneplus'])

In [41]:
d.get('ananya')

'samsumg'

In [42]:
x=3
y=6
x+y

9

In [43]:
x-y


-3

x=x+2

In [52]:
x=3
x=x+2
x

5

In [53]:
x+=2
x

7

In [54]:
x*=3
x

21

In [55]:
a,b=5,6
a

5

In [56]:
b

6

In [57]:
n=7
n


7

In [58]:
n=-n
n

-7

In [59]:
a>b

False

In [60]:
a<b

True

In [61]:
a==b

False

In [62]:
a!=b

True

In [63]:
a=5
b=4
a<8 and b<5

True

In [64]:
a<8 and b<2

False

In [65]:
x=True
x

True

In [66]:
not x

False

In [67]:
a<8 or b<2

True

In [68]:
bin(25)

'0b11001'

In [69]:
0b0101

5

In [70]:
oct(35)

'0o43'

In [71]:
hex(10)

'0xa'

In [72]:
0xf

15

In [73]:
bin(31)

'0b11111'

In [74]:
bin(52)

'0b110100'

In [75]:
0b110011010

410

In [76]:
~15

-16

In [77]:
12 & 13

12

In [78]:
12 | 13

13

In [79]:
12 ^ 13

1

In [80]:
10<<2

40

In [81]:
10>>2

2

In [82]:
x=input("enter 1st number")
y=input("enter 1st number")
z=x+y
print(z)


enter 1st number10
enter 1st number11
1011


In [83]:
x=input("enter 1st number")
a=int(x)
y=input("enter 1st number")
b=int(y)
z=a+b
print(z)

enter 1st number15
enter 1st number20
35


In [84]:
x=int(input("enter 1st number"))
y=int(input("enter 1st number"))
z=x+y
print(z)

enter 1st number1
enter 1st number2
3


In [85]:
ch=input("enter a character")
print(ch)

enter a charactera
a


In [86]:
ch=input("enter a character")
print(ch[0])

enter a characterpqr
p


In [87]:
ch=input("enter a character")[0]
print(ch)

enter a characterpqr
p


In [88]:
result=eval(input("enter an expression"))
print(result)

enter an expression2+5-6
1


In [89]:
nums=[10,20,30,40]
nums

[10, 20, 30, 40]

In [90]:
nums[1]


20

In [91]:
nums[2:]

[30, 40]

In [92]:
nums[-1]

40

In [94]:
names=['ananya','anu','akash']
names

['ananya', 'anu', 'akash']

In [95]:
values=[9.5,'ananya',50]
values

[9.5, 'ananya', 50]

In [96]:
mil=[nums,names]
mil

[[10, 20, 30, 40], ['ananya', 'anu', 'akash']]

In [99]:
nums.append(45)
nums

[10, 20, 30, 40, 45, 45, 45]

In [100]:
nums.insert(2,25)
nums

[10, 20, 25, 30, 40, 45, 45, 45]

In [102]:
nums.remove(45)
nums

[10, 20, 25, 30, 40, 45]

In [103]:
nums.remove(45)
nums

[10, 20, 25, 30, 40]

In [105]:
nums.pop(2)
nums

[10, 20, 30, 40]

In [106]:
nums.pop()

40

In [107]:
nums

[10, 20, 30]

In [111]:
del nums[2:]
nums

[10]

In [113]:
nums.extend([12,15,19])
nums

[10, 12, 15, 19]

In [114]:
min(nums)

10

In [115]:
max(nums)

19

In [116]:
sum(nums)

56

In [118]:
nums.sort()
nums

[10, 12, 15, 19]

In [120]:
tup=(10,20,30,40)
tup

(10, 20, 30, 40)

In [121]:
tup[1]

20

In [122]:
tup[1]=25

TypeError: 'tuple' object does not support item assignment

In [123]:
s={70,10,20,30,40}
s

{10, 20, 30, 40, 70}

In [130]:
s={101,12,78,99,44,509,66}
s

{12, 44, 66, 78, 99, 101, 509}

In [131]:
s[2]

TypeError: 'set' object is not subscriptable

In [135]:
s.pop()

66

In [140]:
s.add(25)
s

{12, 25, 44, 78, 99, 101, 509}

In [142]:
s.remove(12)
s

{25, 44, 78, 99, 101, 509}

max(s)

In [143]:
max(s)

509

In [144]:
min(s)

25

In [145]:
data={1:'ananya',2:'anu',4:'akash'}
data

{1: 'ananya', 2: 'anu', 4: 'akash'}

In [146]:
data[1]

'ananya'

In [147]:
data[3]

KeyError: 3

In [148]:
data.get(1)

'ananya'

In [150]:
print(data.get(3))

None


In [151]:
data.get(3,'not found')

'not found'

In [154]:
keys=['anaya','anu','preetham']
values=['python','java','c++']
data=dict(zip(keys,values))
data

{'anaya': 'python', 'anu': 'java', 'preetham': 'c++'}

In [157]:
data['anaya']

'python'

In [158]:
data['monica']='C'
data

{'anaya': 'python', 'anu': 'java', 'preetham': 'c++', 'monica': 'C'}

In [160]:
del data['preetham']
data

{'anaya': 'python', 'anu': 'java', 'monica': 'C'}

In [163]:
prog={'JS':'Atom','CS':'VS','Python':['Pycharm','Jupyter notebook'],'Java':{'JSE':'Netbeans','JEE':'Eclipse'}}
prog

{'JS': 'Atom',
 'CS': 'VS',
 'Python': ['Pycharm', 'Jupyter notebook'],
 'Java': {'JSE': 'Netbeans', 'JEE': 'Eclipse'}}

In [164]:
prog['JS']

'Atom'

In [165]:
prog['Python']

['Pycharm', 'Jupyter notebook']

In [166]:
prog['Python'][1]

'Jupyter notebook'

In [168]:
prog['Java']

{'JSE': 'Netbeans', 'JEE': 'Eclipse'}

In [169]:
prog['Java']['JEE']

'Eclipse'

In [170]:
if True:
    print("Im right")


Im right


In [171]:
if False:
    print("Im right")

In [172]:
if True:
    print("Im right")
print("hi")

Im right
hi


In [173]:
if False:
    print("Im right")
print("Bye")

Bye


In [175]:
if False:
    print("Im right")
  print("Bye")

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [176]:
x=10
r=x%2
if r==0:
    print("even")

even


In [179]:
x=3
r=x%2
if r==0:
    print("even")
if r==1:
    print("odd")


odd


In [181]:
x=7
r=x%2
if r==0:
    print("even")
else:
    print("odd")

odd


In [182]:
x=10
r=x%2
if r==0:
    print("even")
    if x>5:
        print("great")
    else:
        print("not great")
if r==1:
    print("odd")

even
great


In [183]:
x=2
r=x%2
if r==0:
    print("even")
    if x>5:
        print("great")
    else:
        print("not great")
if r==1:
    print("odd")

even
not great


In [184]:
x=3
if(x==1):
    print("one")
elif(x==2):
    print("two")
elif(x==3):
    print("three")
elif(x==4):
    print("four")
else:
    print("wrong input")

three


In [185]:
x=5
if(x==1):
    print("one")
elif(x==2):
    print("two")
elif(x==3):
    print("three")
elif(x==4):
    print("four")
else:
    print("wrong input")

wrong input


In [187]:
i=1
while i<=5:
    print("hello")
    i=i+1

hello
hello
hello
hello
hello


In [189]:
i=3
while i>=1:
    print("hello",i)
    i=i-1

hello 3
hello 2
hello 1


In [190]:
i=1
j=1
while i<=5:
    print("hello")
    while j<=3:
        print("hi")
        j=j+1
    i=i+1

hello
hi
hi
hi
hello
hello
hello
hello


In [196]:
i=1
j=1
while i<=5:
    print("hello",end=" ")
    while j<=3:
        print("hi",end=" ")
        j=j+1
    i=i+1
    print()

hello hi hi hi 
hello 
hello 
hello 
hello 


In [197]:
i=1

while i<=5:
    print("hello",end=" ")
    j=1
    while j<=3:
        print("hi",end=" ")
        j=j+1
    i=i+1
    print()

hello hi hi hi 
hello hi hi hi 
hello hi hi hi 
hello hi hi hi 
hello hi hi hi 


In [198]:
x=["ananya",15,2.5]
for i in x:
    print(i)

ananya
15
2.5


In [199]:
x="ANANYA"
for i in x:
    print(i)

A
N
A
N
Y
A


In [200]:
for i in range(5):
    print(i)

0
1
2
3
4


In [201]:
for i in range(12,15,1):
    print(i)

12
13
14


In [202]:
for i in range(22,15,-1):
    print(i)

22
21
20
19
18
17
16


In [203]:
for i in range(1,21):
    if i%5==0:
        print(i)

5
10
15
20


In [204]:
x=int(input("How many candiesyou want?"))
i=1
while i<=x:
    print("Candies")
    i+=1

How many candiesyou want?4
Candies
Candies
Candies
Candies


In [206]:
available=10
x=int(input("How many candiesyou want?"))

i=1
while i<=x:
    if i>available:
        break
    print("Candies")
    i+=1
print("bye")

How many candiesyou want?4
Candies
Candies
Candies
Candies
bye


In [208]:
available=6
x=int(input("How many candiesyou want?"))

i=1
while i<=x:
    if i>available:
        print("Out of stock")
        break
    print("Candies")
    i+=1
print("bye")

How many candiesyou want?11
Candies
Candies
Candies
Candies
Candies
Candies
Out of stock
bye


In [213]:
for i in range(1,22):
    if i%3==0 or i%5==0:
        continue
    print(i)


1
2
4
7
8
11
13
14
16
17
19


In [214]:
for i in range(1,21):
    if(i%2!=0):
        pass
    else:
        print(i)

2
4
6
8
10
12
14
16
18
20


In [218]:
nums=[12,15,18,21,28]
for num in nums:
    if num%5==0:
        print(num)

15


In [219]:
nums=[12,15,18,21,25]
for num in nums:
    if num%5==0:
        print(num)

15
25


In [220]:
nums=[12,15,18,21,28]
for num in nums:
    if num%5==0:
        print(num)
        break

15


In [222]:
nums=[12,16,18,21,28]
for num in nums:
    if num%5==0:
        print(num)
    else:
        print("not found")

not found
not found
not found
not found
not found


In [224]:
nums=[12,16,18,21,28]
for num in nums:
    if num%5==0:
        print(num)
else:
        print("not found")

not found


In [226]:
from array import*
vals=array('i',[5,9,-84,2])
print(vals)

array('i', [5, 9, -84, 2])


In [228]:
from array import*
vals=array('i',[5,9,-84,2])
print(vals.buffer_info())

(2175917088928, 4)


In [229]:
from array import*
vals=array('i',[5,9,-84,2])
print(vals.typecode)

i


In [230]:
from array import*
vals=array('i',[5,9,-84,2])
vals.reverse()
print(vals)

array('i', [2, -84, 9, 5])


In [234]:
from array import*
vals=array('i',[5,9,-8,4,2])
print(vals[0])

5


In [235]:
from array import*
vals=array('i',[5,9,-8,4,2])
for i in range(5):
    print(vals[i])

5
9
-8
4
2


In [236]:
from array import*
vals=array('i',[5,9,-8,4,2])
for i in range(len(vals)):
    print(vals[i])

5
9
-8
4
2


In [238]:
from array import*
vals=array('i',[5,9,-8,4,2])
for e in vals:
    print(e)

5
9
-8
4
2


In [246]:
from array import*
vals=array('i',[5,9,-8,4,2])
newArr=array(vals.typecode,(a for a in vals))
for e in newArr:
    print(e)

5
9
-8
4
2


In [245]:
from array import*
vals=array('i',[5,9,-8,4,2])
newArr=array(vals.typecode,(a*a for a in vals))
for e in newArr:
    print(e)

25
81
64
16
4


In [249]:
from array import*
vals=array('i',[5,9,-8,4,2])
newArr=array(vals.typecode,(a*a for a in vals))
i=0
while i<len(newArr):   
    i=i+1
print(newArr)

array('i', [25, 81, 64, 16, 4])


In [251]:
from array import*
arr=array('i',[])
n=int(input("enter the length of the array"))
for i in range(n):
    x=int(input("enter the array elements"))
    arr.append(x)
print(arr)

enter the length of the array4
enter the array elements10
enter the array elements20
enter the array elements30
enter the array elements40
array('i', [10, 20, 30, 40])


In [253]:
from array import*
arr=array('i',[])
n=int(input("enter the length of the array"))
for i in range(n):
    x=int(input("enter the array elements"))
    arr.append(x)
print(arr)
val=int(input("enter the elements to be searched"))
k=0
for e in arr:
    if e==val:
        print(k)
        break
    k=k+1


enter the length of the array4
enter the array elements10
enter the array elements20
enter the array elements30
enter the array elements40
array('i', [10, 20, 30, 40])
enter the elements to be searched30
2


In [254]:
from array import*
arr=array('i',[])
n=int(input("enter the length of the array"))
for i in range(n):
    x=int(input("enter the array elements"))
    arr.append(x)
print(arr)
print(arr.index(val))

enter the length of the array4
enter the array elements10
enter the array elements20
enter the array elements30
enter the array elements40
array('i', [10, 20, 30, 40])
2


In [255]:
from numpy import*
arr=array([1,2,3,4,5,0])
print(arr.dtype)

int32


In [257]:
from numpy import*
arr=array([1,2,3,4,5.0,0])
print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5. 0.]


In [259]:
from numpy import*
arr=array([1,2,3,4,5.0,0])
print(arr.dtype)

float64


In [260]:
from numpy import*
arr=array([1,2,3,4,5,0],float)
print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5. 0.]


In [261]:
from numpy import*
arr=array([1,2,3,4,5,0],int)
print(arr.dtype)
print(arr)

int32
[1 2 3 4 5 0]


In [262]:
from numpy import*
arr=linspace(0,16,17)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


In [263]:
from numpy import*
arr=linspace(0,16,25)
print(arr)

[ 0.          0.66666667  1.33333333  2.          2.66666667  3.33333333
  4.          4.66666667  5.33333333  6.          6.66666667  7.33333333
  8.          8.66666667  9.33333333 10.         10.66666667 11.33333333
 12.         12.66666667 13.33333333 14.         14.66666667 15.33333333
 16.        ]


In [264]:
from numpy import*
arr=arange(0,16,4)
print(arr)

[ 0  4  8 12]


In [265]:
from numpy import*
arr=logspace(0,16,17)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16]


In [266]:
from numpy import*
arr=logspace(1,40,5)
print('%.2f' %arr[4])

10000000000000000303786028427003666890752.00


In [268]:
from numpy import*
arr=zeros(3)
print(arr)

[0. 0. 0.]


In [269]:
from numpy import*
arr=ones(3)
print(arr)

[1. 1. 1.]


In [270]:
from numpy import*
arr=zeros(3,int)
print(arr)

[0 0 0]


In [273]:
from numpy import*
arr1=array([1,2,3,4,5])
arr2=arr1+5
print(arr2)

[ 6  7  8  9 10]


In [274]:
from numpy import*
arr1=array([1,2,3,4,5])
arr2=array([6,7,8,9,10])
arr3=arr2+arr1
print(arr3)

[ 7  9 11 13 15]


In [275]:
from numpy import*
arr1=array([1,2,3,4,5])
print(sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [276]:
from numpy import*
arr1=array([1,2,3,4,5])
print(cos(arr1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [277]:
from numpy import*
arr1=array([1,2,3,4,5])
print(log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [278]:
from numpy import*
arr1=array([1,2,3,4,5])
print(sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [279]:
from numpy import*
arr1=array([1,2,3,4,5])
print(max(arr1))

5


In [280]:
from numpy import*
arr1=array([1,2,3,4,5])
print(min(arr1))

1


In [282]:
from numpy import*
arr1=array([1,2,3,4,5])
arr2=array([6,7,8,9,10])
print(concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7  8  9 10]


In [283]:
from numpy import*
arr1=array([1,2,3,4,5])
arr2=arr1
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


In [284]:
from numpy import*
arr1=array([1,2,3,4,5])
print(id(arr1))

2175922946288


In [286]:
 from numpy import*
arr1=array([1,2,3,4,5])
arr2=arr1.view()
print(id(arr1))
print(id(arr2))

2175922607088
2175922693776


In [287]:
from numpy import*
arr1=array([1,2,3,4,5])
arr2=arr1.view()
arr1[1]=7
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 7 3 4 5]
[1 7 3 4 5]
2175922946288
2175923088912


In [288]:
from numpy import*
arr1=array([1,2,3,4,5])
arr2=arr1.copy()
arr1[1]=7
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 7 3 4 5]
[1 2 3 4 5]
2175922606992
2175922969072


In [292]:
from numpy import*
arr1=array([
              [1,2,3] ,
              [4,5,6]
           
            ])
print(arr1.ndim)

2


In [293]:
from numpy import*
arr1=array([
              [1,2,3] ,
              [4,5,6]
           
            ])
print(arr1.shape)

(2, 3)


In [294]:
from numpy import*
arr1=array([
              [1,2,3] ,
              [4,5,6]
           
            ])
print(arr1.size)

6


In [297]:
from numpy import*
arr1=array([
              [1,2,3,6,2,9] ,
              [4,5,6,7,5,3]
           
            ])
arr2=arr1.flatten()
arr3=arr2.reshape(3,4)
print(arr3)

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [298]:
from numpy import*
arr1=array([
              [1,2,3,6,2,9] ,
              [4,5,6,7,5,3]
           
            ])
arr2=arr1.flatten()
arr3=arr2.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [299]:
from numpy import*
arr1=array([
              [1,2,3] ,
              [4,5,6]
           
            ])
m=matrix(arr1)
print(m)

[[1 2 3]
 [4 5 6]]


In [300]:
from numpy import*
m=matrix('1,2,3;5,7,8;1,9,0')
print(m)

[[1 2 3]
 [5 7 8]
 [1 9 0]]


In [301]:
from numpy import*
m=matrix('1,2,3;5,7,8;1,9,0')
print(m.max())

9


In [302]:
from numpy import*
m=matrix('1,2,3;5,7,8;1,9,0')
print(m.min())

0


In [304]:
from numpy import*
m1=matrix('1,2,3;5,7,8;1,9,0')
m2=matrix('1,2,3;6,7,9;5,9,4')
m3=m2+m1
print(m3)


[[ 2  4  6]
 [11 14 17]
 [ 6 18  4]]


In [305]:
from numpy import*
m1=matrix('1,2,3;5,7,8;1,9,0')
m2=matrix('1,2,3;6,7,9;5,9,4')
m3=m1*m2;
print(m3)

[[ 28  43  33]
 [ 87 131 110]
 [ 55  65  84]]


In [307]:
def greet():
    print("Hello")
    print("good morning")
greet()

Hello
good morning


In [308]:
def greet():
    print("Hello")
    print("good morning")
def add(x,y):
    c=x+y
    print(c)
add(5,4)
greet()

9
Hello
good morning


In [310]:
def greet():
    print("Hello")
    print("good morning")
def add(x,y):
    c=x+y
    return c

greet()
result=add(5,4)
print(result)

Hello
good morning
9


In [311]:
def add_sub(x,y):
    c=x+y
    d=x-y
    return c,d
result1,result2=add_sub(5,4)
print(result1,result2)

9 1


In [312]:
def update(x):
    x=8
    print(x)
update(a)

8


In [313]:
def update(x):
    x=8
    print("x",x)
a=10
update(a)
print("a",a)

x 8
a 10


In [314]:
def update(x):
    print(id(x))
    x=8
    print("x",x)
a=10
print(id(a))
update(a)
print("a",a)

2175800666704
2175800666704
x 8
a 10


In [316]:
def update(lst):
    print(id(lst))
    lst=8
    print("x",lst)
lst=[10,20,30]
print(id(lst))
update(lst)
print("lst",lst)

2175922737088
2175922737088
x 8
lst [10, 20, 30]


In [317]:
def add(a,b):
    c=a+b
    print(c)
add(5,6)

11


In [318]:
def person(name,age):
    print(name)
    print(age)
person(28,'rahul')

28
rahul


In [319]:
def person(name,age):
    print(name)
    print(age-5)
person(28,'rahul')

28


TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [321]:
def person(name,age):
    print(name)
    print(age-5)
person(age=28,name='rahul')

rahul
23


In [322]:
def person(name,age):
    print(name)
    print(age)
person('rahul')

TypeError: person() missing 1 required positional argument: 'age'

In [324]:
def person(name,age=18):
    print(name)
    print(age)
person('rahul')

rahul
18


In [325]:
def sum(a,b):
    c=a+b
    print(c)
sum(5,6)

11


In [326]:
def sum(a,*b):
    
    print(a)
    print(b)
sum(5,6,34,78)

5
(6, 34, 78)


In [327]:
def sum(a,*b):
    c=a
    for i in b:
        c=c+i
    print(c)
sum(5,6,34,78)

123


In [329]:
def person(name,**data):
    print(name)
    print(data)
    
person('navin',age=25,city='mumbai',phoneno=123456789)

navin
{'age': 25, 'city': 'mumbai', 'phoneno': 123456789}


In [330]:
def person(name,**data):
    print(name)
    for i,j in data.items():
        print(i,j)
person('navin',age=25,city='mumbai',phoneno=123456789)     

navin
age 25
city mumbai
phoneno 123456789


In [333]:
def count(lst):
    even=0
    odd=0
    for i in lst:
        if i%2==0:
            even+=1
        else:
            odd+=1
    return even,odd
lst=[10,20,23,43,57,60]
even , odd=count(lst)
print(even)
print(odd)

3
3


In [334]:
def count(lst):
    even=0
    odd=0
    for i in lst:
        if i%2==0:
            even+=1
        else:
            odd+=1
    return even,odd
lst=[10,20,23,43,57,60]
even , odd=count(lst)
print("even:{} and odd:{}".format(even,odd))

even:3 and odd:3


In [336]:
a=10
def something():
    a=15
   
    print("in function",a)
something()
print("outside",a)

in function 15
outside 10


In [337]:
a=10
def something():
    
    print("in function",a)
something()
print("outside",a)

in function 10
outside 10


In [340]:
a=10
def something():
    global a
    a=15
    print("in function",a)
    
something()
print("outside",a)

in function 15
outside 15


In [341]:
a=10
def something():
    global a
    a=15
    print("in function",a)
    a=9
something()
print("outside",a)

in function 15
outside 9


In [342]:
a=10
print(id(a))
def something():
    
    a=15
    x=globals()['a']
    print(id(x))
    print("in function",a)
    
something()
print("outside",a)

2175800666704
2175800666704
in function 15
outside 10


In [343]:
a=10
print(id(a))
def something():
    
    a=15
    x=globals()['a']
    print(id(x))
    print("in function",a)
    globals()['a']=9
something()
print("outside",a)

2175800666704
2175800666704
in function 15
outside 9


In [35]:
def greet():
    print("Hello")
    greet()
greet()

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hell

RecursionError: maximum recursion depth exceeded while calling a Python object

In [1]:
import sys
print(sys.getrecursionlimit())
def greet():
    print("Hello")
    greet()


3000


In [3]:
import sys
sys.setrecursionlimit(2000)
print(sys.getrecursionlimit())

def greet():
    print("Hello")
    greet()


2000


In [7]:
import sys
sys.setrecursionlimit(2000)
print(sys.getrecursionlimit())
i=0
def greet():
    global i
    i+=1
    print("Hello",i)
    greet()
greet()

2000
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14
Hello 15
Hello 16
Hello 17
Hello 18
Hello 19
Hello 20
Hello 21
Hello 22
Hello 23
Hello 24
Hello 25
Hello 26
Hello 27
Hello 28
Hello 29
Hello 30
Hello 31
Hello 32
Hello 33
Hello 34
Hello 35
Hello 36
Hello 37
Hello 38
Hello 39
Hello 40
Hello 41
Hello 42
Hello 43
Hello 44
Hello 45
Hello 46
Hello 47
Hello 48
Hello 49
Hello 50
Hello 51
Hello 52
Hello 53
Hello 54
Hello 55
Hello 56
Hello 57
Hello 58
Hello 59
Hello 60
Hello 61
Hello 62
Hello 63
Hello 64
Hello 65
Hello 66
Hello 67
Hello 68
Hello 69
Hello 70
Hello 71
Hello 72
Hello 73
Hello 74
Hello 75
Hello 76
Hello 77
Hello 78
Hello 79
Hello 80
Hello 81
Hello 82
Hello 83
Hello 84
Hello 85
Hello 86
Hello 87
Hello 88
Hello 89
Hello 90
Hello 91
Hello 92
Hello 93
Hello 94
Hello 95
Hello 96
Hello 97
Hello 98
Hello 99
Hello 100
Hello 101
Hello 102
Hello 103
Hello 104
Hello 105
Hello 106
Hello 107
Hello 108
Hello 109
Hello 110
Hel

RecursionError: maximum recursion depth exceeded while calling a Python object

In [8]:
def square(a):
    return a*a
result=square(5)
print(result)

25


In [10]:
f=lambda a:a*a
result=f(5)
print(result)

25


In [11]:
f=lambda a,b:a+b
result=f(5,6)
print(result)

11


In [13]:
def is_even(n):
    return n%2==0
    
nums=[1,2,3,4,5,6,7]
even=list(filter(is_even,nums))
print(even)

[2, 4, 6]


In [18]:
def update(n):
    return n+2
nums=[1,2,3,4,5,6,7]
even=list(filter(lambda n:n%2==0,nums))
doubles=list(map(update,even))
print(doubles)

[4, 6, 8]


In [20]:

nums=[1,2,3,4,5,6,7]
even=list(filter(lambda n:n%2==0,nums))
doubles=list(map(lambda n:n*2,even))
print(doubles)

[4, 8, 12]


In [22]:
from functools import reduce
def add_all(a,b):
    return a+b
nums=[1,2,3,4,5,6,7]
even=list(filter(lambda n:n%2==0,nums))
doubles=list(map(lambda n:n*2,even))
sum=reduce(add_all,doubles)
print(sum)

24


In [24]:
from functools import reduce
def add_all(a,b):
    return a+b
nums=[1,2,3,4,5,6,7]
even=list(filter(lambda n:n%2==0,nums))
doubles=list(map(lambda n:n*2,even))
print(doubles)
sum=reduce(lambda a,b:a+b,doubles)
print(sum)

[4, 8, 12]
24


In [26]:
def div(a,b):
    print(a/b)
div(2,4)

0.5


In [28]:
def div(a,b):
    if a<b:
         a,b=b,a
    print(a/b)
div(2,4)

2.0


In [34]:
def div(a,b):
    print(a/b)
def smart_div(func):
    def inner(a,b):
        if a<b:
            a,b=b,a
        return func(a,b)
    return inner
div1=smart_div(div)
div1(2,4)

2.0


In [37]:
def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def multi(a,b):
    return a*b
def div(a,b):
    return a/b

In [38]:
a=9
b=7
c=add(a,b)
print(c)

16


In [39]:
a=9
b=7
c=sub(a,b)
print(c)

2


In [40]:
print("hello"+ __name__)

hello__main__


In [43]:

print("Demo says:"+__name__)

Demo says:__main__


In [44]:
print("hello")
print("welcome user")

hello
welcome user


In [45]:
class Computer:
    def config():
        print("i5,16gb,1TB")
a='8'
com1=Computer()
print(type(com1))

<class '__main__.Computer'>


In [48]:
class Computer:
    def config():
        print("i5,16gb,1TB")

a='8'
print(type(a))
com1=Computer()
print(type(com1))

<class 'str'>
<class '__main__.Computer'>


In [47]:
class Computer:
    def config():
        print("i5,16gb,1TB")
x=9
print(type(x))
a='8'
print(type(a))
com1=Computer()
print(type(com1))

<class 'int'>
<class 'str'>
<class '__main__.Computer'>


In [49]:
class Computer:
    def config():
        print("i5,16gb,1TB")
com1=Computer()
Computer.config()

i5,16gb,1TB


In [50]:
class Computer:
    def config(self):
        print("i5,16gb,1TB")
com1=Computer()
Computer.config()

TypeError: config() missing 1 required positional argument: 'self'

In [51]:
class Computer:
    def config(self):
        print("i5,16gb,1TB")
com1=Computer()
Computer.config(com1)

i5,16gb,1TB


In [52]:
class Computer:
    def config(self):
        print("i5,16gb,1TB")
com1=Computer()
com2=Computer()
Computer.config(com1)
Computer.config(com2)

i5,16gb,1TB
i5,16gb,1TB


In [53]:
class Computer:
    def config(self):
        print("i5,16gb,1TB")
com1=Computer()
com2=Computer()
Computer.config(com1)
Computer.config(com2)
com1.config()
com2.config()

i5,16gb,1TB
i5,16gb,1TB
i5,16gb,1TB
i5,16gb,1TB


In [54]:
class Computer:
    def config(self):
        print("i5,16gb,1TB")
com1=Computer()
com2=Computer()
Computer.config(com1)
Computer.config(com2)
com1.config()
com2.config()
a=5
a.bit_length()

i5,16gb,1TB
i5,16gb,1TB
i5,16gb,1TB
i5,16gb,1TB


3

In [57]:
class Computer:
    def __init__(self):
        print("in init")
    def config(self):
        print("i5,16gb,1TB")
com1=Computer()
com2=Computer()

com1.config()
com2.config()

in init
in init
i5,16gb,1TB
i5,16gb,1TB


In [60]:
class Computer:
    def __init__(self,cpu,ram):
        self.cpu=cpu
        self.ram=ram
    def config(self):
        print("Config is",self.cpu,self.ram)
com1=Computer('i5',16)
com2=Computer('Ryzen 3',8)

com1.config()
com2.config()

Config is i5 16
Config is Ryzen 3 8


In [61]:
class Computer:
    pass
c1=Computer()
print(id(c1))

1825500587200


In [62]:
class Computer:
    pass
c1=Computer()
c2=Computer()
print(id(c1))
print(id(c2))


1825523185936
1825523186656


In [1]:
class Computer:
    def __init__(self):
        self.name="Ananya"
        self.age=10
c1=Computer()
c2=Computer()
print(c1.name)
print(c2.name)

Ananya
Ananya


In [3]:
class Computer:
    def __init__(self):
        self.name="Ananya"
        self.age=10
c1=Computer()
c2=Computer()
c1.name="Rashi"
print(c1.name)
print(c2.name)

Rashi
Ananya


In [4]:
class Computer:
    def __init__(self):
        self.name="Ananya"
        self.age=10
c1=Computer()
c2=Computer()
c1.name="Rashi"
c1.age=40
print(c1.age)
print(c2.age)

40
10


In [5]:
class Computer:
    def __init__(self):
        self.name="Ananya"
        self.age=10
    def update(self):
        self.age=30
c1=Computer()
c2=Computer()
c1.name="Rashi"
c1.age=40
c1.update()
print(c1.age)
print(c2.age)

30
10


In [6]:
class Computer:
    def __init__(self):
        self.name="Ananya"
        self.age=10
    def update(self):
        self.age=30
    def compare(self,other):
        if self.age==other.age:
            return True
        else:
            return False
    
    
c1=Computer()

c2=Computer()
if c1.compare(c2):
    print("they are same")

print(c1.age)
print(c2.age)

they are same
10
10


In [7]:
class Computer:
    def __init__(self):
        self.name="Ananya"
        self.age=10
    def update(self):
        self.age=30
    def compare(self,other):
        if self.age==other.age:
            return True
        else:
            return False
    
    
c1=Computer()
c1.age=30
c2=Computer()
if c1.compare(c2):
    print("they are same")
else:
    print("different")

print(c1.age)
print(c2.age)

different
30
10


In [8]:
class Car:
    def __init__(self):
        self.mil=10
        self.com="BMW"
c1=Car()
c2=Car()
print(c1.com,c1.mil)
print(c2.com,c2.mil)

BMW 10
BMW 10


In [9]:
class Car:
    def __init__(self):
        self.mil=10
        self.com="BMW"
c1=Car()
c2=Car()
c1.mil=8
print(c1.com,c1.mil)
print(c2.com,c2.mil)

BMW 8
BMW 10


In [12]:
class Car:
    wheels=4
    def __init__(self):
        self.mil=10
        self.com="BMW"
c1=Car()
c2=Car()
c1.mil=8
print(c1.com,c1.mil,c1.wheels)
print(c2.com,c2.mil,c2.wheels)

BMW 8 4
BMW 10 4


In [13]:
class Car:
    wheels=4
    def __init__(self):
        self.mil=10
        self.com="BMW"
c1=Car()
c2=Car()
Car.wheels=5
c1.mil=8
print(c1.com,c1.mil,c1.wheels)
print(c2.com,c2.mil,c2.wheels)

BMW 8 5
BMW 10 5


In [14]:
class Student:
    school='Telusko'
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def avg(self):
        return(self.m1+self.m2+self.m3)/3
s1=Student(10,20,30)
s2=Student(12,24,36)
print(s1.avg())

20.0


In [15]:
class Student:
    school='Telusko'
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def avg(self):
        return(self.m1+self.m2+self.m3)/3
s1=Student(10,20,30)
s2=Student(12,24,36)
print(s2.avg())

24.0


In [16]:
class Student:
    school='Telusko'
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def avg(self):
        return(self.m1+self.m2+self.m3)/3
    def get_m1(self):
        return self.m1
    def set_m1(self,value):
        self.m1=value
s1=Student(10,20,30)
s2=Student(12,24,36)
print(s1.avg())

20.0


In [17]:
  class Student:
    school='Telusko'
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def avg(self):
        return(self.m1+self.m2+self.m3)/3
    def info(cls):
        return cls.school
s1=Student(10,20,30)
s2=Student(12,24,36)
print(s1.avg())
print(Student.info())

20.0


TypeError: info() missing 1 required positional argument: 'cls'

In [18]:
class Student:
    school='Telusko'
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def avg(self):
        return(self.m1+self.m2+self.m3)/3
    @classmethod
    def info(cls):
        return cls.school
s1=Student(10,20,30)
s2=Student(12,24,36)
print(s1.avg())
print(Student.info())

20.0
Telusko


In [23]:
class Student:
    school='Telusko'
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def avg(self):
        return(self.m1+self.m2+self.m3)/3
    @classmethod
    def getSchool(cls):
        return cls.school
    @staticmethod
    def info():
        print("this is student class..in abc module")
s1=Student(10,20,30)
s2=Student(12,24,36)
print(s1.avg())
print(Student.getSchool())
Student.info()

20.0
Telusko
this is student class..in abc module


In [24]:
class Student:
    def __init__(self,name,rollno):
        self.name=name
        self.rollno=rollno
s1=Student('ananya',7)
s2=Student('Jenny',14)
print(s1.name,s1.rollno)

ananya 7


In [26]:
class Student:
    def __init__(self,name,rollno):
        self.name=name
        self.rollno=rollno
    def show(self):
        print(self.name,self.rollno)
s1=Student('ananya',7)
s2=Student('Jenny',14)
s1.show()
s2.show()

ananya 7
Jenny 14


In [28]:
class Student:
    def __init__(self,name,rollno):
        self.name=name
        self.rollno=rollno
        self.lap=self.Laptop
    def show(self):
        print(self.name,self.rollno)
    class Laptop:
        def __init__(self):
            self.brand='HP'
            self.cpu='i5'
            self.ram=8
s1=Student('ananya',7)
s2=Student('Jenny',14)
s1.show()
s2.show()
lap1=s1.lap
lap2=s2.lap
print(id(lap1))
print(id(lap2))

ananya 7
Jenny 14
2275540601248
2275540601248


In [30]:
class Student:
    def __init__(self,name,rollno):
        self.name=name
        self.rollno=rollno
        self.lap=self.Laptop()
    def show(self):
        print(self.name,self.rollno)
        self.lap.show()
    class Laptop:
        def __init__(self):
            self.brand='HP'
            self.cpu='i5'
            self.ram=8
        def show(self):
            print(self.brand,self.cpu,self.ram)
s1=Student('ananya',7)
s2=Student('Jenny',14)
s1.show()
s2.show()


ananya 7
HP i5 8
Jenny 14
HP i5 8


In [36]:
class A:
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")


a1 = A()
a1.feature1()
a1.feature2()

Feature 1 working
Feature 2 working


In [37]:
class A:
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B(A):
    def feature3(self):
        print("Feature 1 working")
    def feature4(self):
        print("Feature 2 working")

a1 = A()
a1.feature1()
a1.feature2()
b1=B()
b1.feature1()

Feature 1 working
Feature 2 working
Feature 1 working


In [38]:
class A:
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B(A):
    def feature3(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
class C(B):
     def feature5(self):
        print("Feature 5 working")
   
a1 = A()
a1.feature1()
a1.feature2()
b1=B()
b1.feature1()
c1=C()
c1.feature5()

Feature 1 working
Feature 2 working
Feature 1 working
Feature 5 working


In [41]:
class A:
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B():
    def feature3(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
class C(A,B):
     def feature5(self):
        print("Feature 5 working")
a1 = A()
a1.feature1()
a1.feature2()
b1=B()
b1.feature4()
c1=C()
c1.feature5()

Feature 1 working
Feature 2 working
Feature 4 working
Feature 5 working


In [47]:
class A:
    def __init__(self):
        print("in A init")
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B(A):
    def feature3(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
a1=A()


in A init


In [48]:
class A:
    def __init__(self):
        print("in A init")
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B(A):
    def feature3(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
a1=B()


in A init


In [49]:
class A:
    def __init__(self):
        print("in A init")
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B(A):
    def __init__(self):
        print("in B init")
    def feature1(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
a1=B()


in B init


In [50]:
class A:
    def __init__(self):
        print("in A init")
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B(A):
    def __init__(self):
        super().__init__()
        print("in B init")
    def feature1(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
a1=B()


in A init
in B init


In [52]:
class A:
    def __init__(self):
        print("in A init")
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B():
    def __init__(self):
        super().__init__()
        print("in B init")
    def feature1(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
class C(A,B):
    def __init__(self):
        print("in C init")
a1=C()

in C init


In [55]:
class A:
    def __init__(self):
        print("in A init")
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B():
    def __init__(self):
        super().__init__()
        print("in B init")
    def feature1(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
class C(A,B):
    def __init__(self):
        super().__init__()
        
        print("in C init")
a1=C()

in A init
in C init


In [57]:
class A:
    def __init__(self):
        print("in A init")
    def feature1(self):
        print("Feature 1-A working")
    def feature2(self):
        print("Feature 2 working")
class B():
    def __init__(self):
        super().__init__()
        print("in B init")
    def feature1(self):
        print("Feature 1-B working")
    def feature4(self):
        print("Feature 4 working")
class C(A,B):
    def __init__(self):
        super().__init__()
        
        print("in C init")
a1=C()
a1.feature1()

in A init
in C init
Feature 1-A working


In [60]:
class A:
    def __init__(self):
        print("in A init")
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")
class B():
    def __init__(self):
        super().__init__()
        print("in B init")
    def feature1(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")
class C(A,B):
    def __init__(self):
        super().__init__()
        
        print("in C init")
    def feat(self):
        super().feature2()
a1=C()
a1.feat()

in A init
in C init
Feature 2 working


In [63]:
class Python:
    def execute(self):
        print("Compliling")
        print("Running")
class Laptop:
    def code(self,ide):
        ide.execute()
ide=Python()
lap1=Laptop()
lap1.code(ide)

Compliling
Running


In [64]:
class Python:
    def execute(self):
        print("Compliling")
        print("Running")
class MyEditor:
    def execute(self):
        print("Spell Check")
        print("Convention Check")
        print("Compliling")
        print("Running")
class Laptop:
    def code(self,ide):
        ide.execute()
ide=MyEditor()
lap1=Laptop()
lap1.code(ide)

Spell Check
Convention Check
Compliling
Running


In [65]:
a=5
b='World'
print(a+b)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [66]:
a=5
b=6
print(a+b)

11


In [67]:
a=5
b=6
print(a+b)
print(int.__add__(a,b))

11
11


In [68]:
class Student():
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
s1=Student(49,33)
s2=Student(50,40)
s3=s1+s2

TypeError: unsupported operand type(s) for +: 'Student' and 'Student'

In [72]:
class Student():
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def __add__(self,other):
        m1=self.m1+other.m1
        m2=self.m2+other.m2
        s3=Student(m1,m2)
        return s3
s1=Student(49,33)
s2=Student(50,40)
s3=s1 + s2
print(s3.m1)

99


In [77]:
class Student():
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def __add__(self,other):
        m1=self.m1+other.m1
        m2=self.m2+other.m2
        s3=Student(m1,m2)
        return s3
    def __gt__(self,other):
        r1=self.m1+self.m2
        r2=other.m1+other.m2
        if r1>r2:
            return True
        else:
            return False
s1=Student(49,33)
s2=Student(50,40)
s3=s1 + s2
if s1>s2:
    print("s1 wins")
else:
    print("s2 wins")

s2 wins


In [78]:
class Student():
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def __add__(self,other):
        m1=self.m1+other.m1
        m2=self.m2+other.m2
        s3=Student(m1,m2)
        return s3
    def __gt__(self,other):
        r1=self.m1+self.m2
        r2=other.m1+other.m2
        if r1>r2:
            return True
        else:
            return False
s1=Student(49,33)
s2=Student(50,40)
s3=s1 + s2
if s1>s2:
    print("s1 wins")
else:
    print("s2 wins")
a=9
print(a)

s2 wins
9


In [85]:
class Student():
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def __add__(self,other):
        m1=self.m1+other.m1
        m2=self.m2+other.m2
        s3=Student(m1,m2)
        return s3
    def __gt__(self,other):
        r1=self.m1+self.m2
        r2=other.m1+other.m2
        if r1>r2:
            return True
        else:
            return False
    def __str__(self):
        return self.m1,self.m2
s1=Student(49,33)
s2=Student(50,40)
s3=s1 + s2
if s1>s2:
    print("s1 wins")
else:
    print("s2 wins")
a=9
print(a.__str__())
print(s1.__str__())

s2 wins
9
(49, 33)


In [86]:
class Student():
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def __add__(self,other):
        m1=self.m1+other.m1
        m2=self.m2+other.m2
        s3=Student(m1,m2)
        return s3
    def __gt__(self,other):
        r1=self.m1+self.m2
        r2=other.m1+other.m2
        if r1>r2:
            return True
        else:
            return False
    def __str__(self):
        return '{} {} '.format(self.m1,self.m2)
s1=Student(49,33)
s2=Student(50,40)
s3=s1 + s2
if s1>s2:
    print("s1 wins")
else:
    print("s2 wins")
a=9
print(a.__str__())
print(s1)
print(s2)

s2 wins
9
49 33 
50 40 


In [90]:
class Student:
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def sum(self,a,b,c):
        s=a+b+c
        return s
s1=Student(50,60)
print(s1.sum(5,8,9))

22


In [92]:
class Student:
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def sum(self,a=None,b=None,c=None):
        s=a+b+c
        return s
s1=Student(50,60)
print(s1.sum(5,8,6))

19


In [93]:
class Student:
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def sum(self,a=None,b=None,c=None):
        s=0
        if a!=None and b!=None and c!=None:
            s=a+b+c
        elif a!=None and b!=None:
            s=a+b
        else:
            s=a
        return s
s1=Student(50,60)
print(s1.sum(5,8))

13


In [94]:
class Student:
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def sum(self,a=None,b=None,c=None):
        s=0
        if a!=None and b!=None and c!=None:
            s=a+b+c
        elif a!=None and b!=None:
            s=a+b
        else:
            s=a
        return s
s1=Student(50,60)
print(s1.sum(5))

5


In [96]:
class A:
    def show(self):
        print("in A show")
class B(A):
    pass

a1=B()
a1.show()
    

in A show


In [97]:
class A:
    def show(self):
        print("in A show")
class B(A):
    def show(self):
        print("in B show")

a1=B()
a1.show()
    

in B show


In [102]:
from abc import ABC,abstractmethod
class Computer(ABC):
    @abstractmethod
    def process(self):
        pass
class Laptop(Computer):
    def process(self):
        print("its running")
    
com1=Laptop()
com1.process()

its running


In [104]:
from abc import ABC,abstractmethod
class Computer(ABC):
    @abstractmethod
    def process(self):
        pass
class Laptop(Computer):
    def process(self):
        print("its running")
class Programmer:
    def work(self):
        print("Solving Bugs")
com1=Laptop()
prog1=Programmer()
prog1.work()
com1.process()

Solving Bugs
its running


In [110]:
from abc import ABC,abstractmethod
class Computer(ABC):
    @abstractmethod
    def process(self):
        pass
class Laptop(Computer):
    def process(self):
        print("its running")
class Whiteboard:
    def write(self):
        print("its writing")
        print("its writing")
class Programmer:
    def work(self,com):
        print("Solving Bugs")
        com.process()
com1=Laptop()
prog1=Programmer()
prog1.work(com1)


Solving Bugs
its running


In [112]:
a=5
b=2
print(a/b)
print("Bye")

2.5
Bye


In [113]:
a=5
b=0
print(a/b)
print("Bye")

ZeroDivisionError: division by zero

In [115]:
a=5
b=0
try:
    print(a/b)
    
except Exception:
    print("Hey, you cannot divide by zero")
print("Bye")

Hey, you cannot divide by zero
Bye


In [116]:
a=5
b=0
try:
    print(a/b)
    
except Exception as e:
    print("Hey, you cannot divide by zero",e)
print("Bye")

Hey, you cannot divide by zero division by zero
Bye


In [117]:
a=5
b=0
try:
    print("Resource open")
    print(a/b)
    print("resource close")
except Exception as e:
    print("Hey, you cannot divide by zero",e)
print("Bye")

Resource open
Hey, you cannot divide by zero division by zero
Bye


In [119]:
a=5
b=2
try:
    print("Resource open")
    print(a/b)
    
except Exception as e:
    print("Hey, you cannot divide by zero",e)
finally:
    print("resource closed")
print("Bye")

Resource open
2.5
resource closed
Bye


In [120]:
a=5
b=2
try:
    print("Resource open")
    print(a/b)
    k=int(input("Enter a number"))
    print(k)
except Exception as e:
    print("Hey, you cannot divide by zero",e)
finally:
    print("resource closed")
print("Bye")

Resource open
2.5
Enter a number6
6
resource closed
Bye


In [123]:
a=5
b=2
try:
    print("Resource open")
    print(a/b)
    k=int(input("Enter a number"))
    print(k)
except ZeroDivisionError as e:
    print("Hey, you cannot divide by zero",e)
except ValueError as e:
    print("Invalid input")
except Exception as e:
    print("something went wrong")
finally:
    print("resource closed")
print("Bye")

Resource open
2.5
Enter a numberint
Invalid input
resource closed
Bye


In [125]:
class Hello:
    def run(self):
        for i in range(5):
            print("hello")
class Hi:
    def run(self):
        for i in range(5):
            print("hi")
t1=Hello()
t2=Hi()
t1.run()
t2.run()

hello
hello
hello
hello
hello
hi
hi
hi
hi
hi


In [144]:
from time import sleep
from threading import*

class Hello(Thread):
    def run(self):
        for i in range(5):
            print("hello")


class Hi(Thread):
    def run(self):
        for i in range(5):
            print("hi")

t1=Hello()
t2=Hi()
t1.start()
sleep(0.2)
t2.start()
t1.join()
t2.join()
print("bye")

hello
hello
hello
hello
hello
hi
hi
hi
hi
hi
bye
hello
hi
hello
hi
hello
hi
hello
hi
hello
hi


In [146]:
f=open('Mydata','r')
print(f.readline())

FileNotFoundError: [Errno 2] No such file or directory: 'Mydata'